language: node_js
node_js:
- stable
branches:
  only:
  - gh-pages
after_success:
  - bash scripts/deploy.sh

script:
- npm i
- npm run test
deploy:
  local_dir: gh-pages
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: build_gh
