language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- npm i
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: AzA8zdcKeIk2y2XOlVhSMgwXLJBIQzzBg7xF/pQQDVCU2taQwP8mPW5VbdIKwxOdvYUHGNPQZSRAB3fImlFaPR4J5jpMA+hFdaGgwyjqdU7r5eX5Jch5uRinX8C5xKUxP4A/TcrY/3vZ6oVnjTEfr0B7v1evDo68KljBuZCU8edpRwBQIH0I/iGmnfrQpNqg232TW88vf/itdPACOn4/QCAn4RPxdWSJ/Yk8l4wV4KPcrl1X4c8PMo75lqxbz1yZ9Ox5vdA/ywgv48B+lhB1vN3hFFrC/R+sPUuKUctOfXHsmIA5VQvxiZaU5uAWOkNDF6m5qlrSAgqVKOwnw2lhEdcMfPLAkzE+XECrIS6KSIhB6nN4Bo4IPUs0y/DFYn3q9wgUy0ttl4fh3/218Sbybpg7pwNwveIDvZs6iktjVkI3BGDfrilRPHRiJGxXMJ24PPBSsWmoyQkx0ZHCXEDd6KVw/fPGGoho2lqPiuEoils0nIk0AFAwtPHm1AIvEnxIyJuO7V0h8TxyzNluekAUk/+OUSh/qRrxqaIuA5lhbjynlct/2oJQdE/HI1hcngegCfQT4Nkn+dp7juNh0ZstFWImOe3wDOgyFEM/DH3BG1DV7ZJElmRf7zbtHat7bUx+WBJnQKUtkYmRhMHEJwHIEHNsgX4Pgu0z5+dNkzfCc5s=
  app: enigmatic-sea-32641
